[package]
name = "voice_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ufmt = "0.1.0"
heapless = { version = "0.7.3", features = ["ufmt-impl", "defmt-impl"] }

[lib]
name = "voice_lib"
